apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: uctoservis-ingress
  namespace: default
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: grav-uctoservis-svc
              servicePort: 80
